name: blendate.com
favicon: null
layout_spectrum: 0.25768280192278326
typography_spectrum: 0.009668592130765319
title: Single Parents meet Single Parents
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f1'
    - '#2b2a25'
    - '#97a1ad'
    - '#a16b3d'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.9693416066002101
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
